questions=[
  {
    category:"Faith",
    sequence:1,
    affirmation:"I believe in Christ and accept him as my Savior.",
    scripture:"2 Nephi 25:29",
    value:5,
    thoughts:"I always believe at some leve and I accept Jesus Christ as my Savior. \n\
              I'm still learning how to receive Him fully into my life. "
  },
  {
    category:"Faith",
    sequence:2,
    affirmation:"I feel confident that God loves me.",
    scripture:"1 Nephi 11:17",
    value:3,
    thoughts:"I have felt more confident lately that I believe in the past. \n\
      I've turned my heart to more sincere prayer. I believe that He is directing my life. \n\
      I believe that he is helping me grow."
    
  },
  {
    category:"Faith",
    sequence:3,
    affirmation:"I trust the Savior enough to accept His will and do whatever he asks.",
    scripture:"1 Nephi 3:7"
  },
  {
    category:"Faith",
    sequence:4,
    affirmation:"I firmly believe that through the Atonement of Jesus Christ I can be forgiven of all my sins.",
    scripture:"Enos 1:5-8"
  },
  {
    category:"",
    sequence:1,
    affirmation:"",
    scripture:""
  },
  {
    category:"",
    sequence:1,
    affirmation:"",
    scripture:""
  },
  {
    category:"",
    sequence:1,
    affirmation:"",
    scripture:""
  },
  {
    category:"",
    sequence:1,
    affirmation:"",
    scripture:""
  },
  {
    category:"",
    sequence:1,
    affirmation:"",
    scripture:""
  },
  {
    category:"",
    sequence:1,
    affirmation:"",
    scripture:""
  },
  {
    category:"",
    sequence:1,
    affirmation:"",
    scripture:""
  },
  {
    category:"",
    sequence:1,
    affirmation:"",
    scripture:""
  },
  {
    category:"",
    sequence:1,
    affirmation:"",
    scripture:""
  },
  {
    category:"",
    sequence:1,
    affirmation:"",
    scripture:""
  },
  {
    category:"",
    sequence:1,
    affirmation:"",
    scripture:""
  },
  {
    category:"",
    sequence:1,
    affirmation:"",
    scripture:""
  },
  {
    category:"",
    sequence:1,
    affirmation:"",
    scripture:""
  },
  {
    category:"",
    sequence:1,
    affirmation:"",
    scripture:""
  },
  {
    category:"",
    sequence:1,
    affirmation:"",
    scripture:""
  },
  {
    category:"",
    sequence:1,
    affirmation:"",
    scripture:""
  },
  {
    category:"",
    sequence:1,
    affirmation:"",
    scripture:""
  },
  {
    category:"",
    sequence:1,
    affirmation:"",
    scripture:""
  },
  {
    category:"",
    sequence:1,
    affirmation:"",
    scripture:""
  },
  {
    category:"",
    sequence:1,
    affirmation:"",
    scripture:""
  },
  {
    category:"",
    sequence:1,
    affirmation:"",
    scripture:""
  },
  {
    category:"",
    sequence:1,
    affirmation:"",
    scripture:""
  },
  {
    category:"",
    sequence:1,
    affirmation:"",
    scripture:""
  },
  {
    category:"",
    sequence:1,
    affirmation:"",
    scripture:""
  },
  {
    category:"",
    sequence:1,
    affirmation:"",
    scripture:""
  },
  {
    category:"",
    sequence:1,
    affirmation:"",
    scripture:""
  },
  {
    category:"",
    sequence:1,
    affirmation:"",
    scripture:""
  },
  {
    category:"",
    sequence:1,
    affirmation:"",
    scripture:""
  },
  {
    category:"",
    sequence:1,
    affirmation:"",
    scripture:""
  },
  {
    category:"",
    sequence:1,
    affirmation:"",
    scripture:""
  },
  {
    category:"",
    sequence:1,
    affirmation:"",
    scripture:""
  },
  {
    category:"",
    sequence:1,
    affirmation:"",
    scripture:""
  },
  {
    category:"",
    sequence:1,
    affirmation:"",
    scripture:""
  }
  


]